[package]
name = "one-weekend"
version = "0.1.0"
authors = ["Chris Butler <chrisbutler296@gmail.com>"]
edition = "2018"

[dependencies]
rand = "^0.5.5"
pbr = "^1.0"

[dependencies.image]
version = "^0.20"
default-features = false
features = ["png_codec"]

[profile.release]
debug = true
